service: sergei-toptalo-import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SQS_URL: !ImportValue CatalogItemsSQSQueue
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::sergei-toptalo-import-service"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::sergei-toptalo-import-service/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource: !ImportValue CatalogItemsSQSQueueARN

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

package:
#  include:
#    - include-me.js
#    - include-me-dir/**
  exclude:
    - build/**
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: sergei-toptalo-import-service
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
